### ISSUE TITLE
Methods with the same name JCommentsObjectInfo

### ISSUE THREAD

**Issue by ramonlopez23** [exstreme/Jcomments-Recaptcha2#1]
Hi! 
Thanks for this great patch, it is really needed. I get the following error, using Joomla 3.6.5 and PHP 7:
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; JCommentsObjectInfo has a deprecated constructor in /home2/xxx/public_html/xxxx.com/components/com_jcomments/classes/objectinfo.php on line 17

Thanks,

**Comment by exstreme** [comment]
Hello!
Add small fix, check it!
Thanks for using!

**Comment by ramonlopez23** [comment]
HI great!!!!
Thanks for the fast reply..

Installed and check the error log a few hour later, and now it shows others warnings... :(

PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; JoomlaTuneAjaxResponse has a deprecated constructor in /home2/xxx/public_html/xxxx.com/components/com_jcomments/libraries/joomlatune/ajax.php on line 19
[14-Feb-2017 14:29:41 America/Chicago] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; JoomlaTuneAjax has a deprecated constructor in /home2/xxx/public_html/xxx.com/components/com_jcomments/libraries/joomlatune/ajax.php on line 147

I don't know if this affect the site, but the error log get quite big very fast with this messages.

**Comment by exstreme** [comment]
Hi!
More fixes!
We don't need deprecated in our logs, comment if you find more issues!

**Comment by ramonlopez23** [comment]
Great, That was so fast. Thanks!!!

So far so good, I'l keep and eye on my site error log, i'l let you know if anything comes up.

Again, thanks so much for this much needed patch.

**Comment by exstreme** [comment]
Some small issues were explored in component.
You can update too
