### ISSUE TITLE
Invisible Captcha and JComments

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-Recaptcha2#11]
Hello, 
Would be great to make JComments work with Invisible Captcha plugin.
Now I am selecting Invisible Captcha in JComments settings, but the component still displays ReCaptcha 2.

**Comment by twister65** [comment]
reCaptcha invisible is implemented here:
https://github.com/twister65/com_jcomments/commit/c878f6b4d297d9a4f2eede3dfcff62be69b15335
https://github.com/twister65/com_jcomments

**Comment by exstreme** [comment]
#12 merged

**Comment by Sulpher** [comment]
@twister65 what is your fork based on? On the original JComments or on the fork by exstreme?
It's important since I prefer the solution from exstreme - it's patched to work with PHP 7.x while the original version is not.

**Comment by twister65** [comment]
It is based on the original JComments, but it is also patched to work with PHP 7.x.
But Google reCaptcha doesn't work with Ajax, you can't hide the form.
