### ISSUE TITLE
Fix for PHP 7.2

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-Recaptcha2#14]
Error with JComments and PHP 7.2:
Uncaught SyntaxError: Unexpected token < 

To fix it:
Open components/com_jcomments/tpl/default/tpl_form.php

Find:
if (count($customBBCodes)) {

Replace it to:
if (!empty($customBBCodes)) {

**Comment by exstreme** [comment]
https://github.com/exstreme/Jcomments-Recaptcha2/commit/8034867da59ad27d84f8c6cb7aaac2b08ae728f8#diff-dac33d7af734d53c67d417292cd6935c already integrated

**Comment by Sulpher** [comment]
Ah, I used a custom theme. Sorry :-)
