### ISSUE TITLE
The form does not work if multilingual feature is enabled

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-Recaptcha2#16]
There is a problem in multilingual sites.
If **System - Language Filter** plugin enabled, JComments make a mess:
there is a default template instead of a custom template and no reply form is available.

How comments look like with custom template:
![Screen Shot 2019-08-28 at 01 54 40](https://user-images.githubusercontent.com/3432048/63813657-e5a93780-c936-11e9-9d01-4223a1f3c9b2.png)

How it is if the language filter plugin enabled:
![Screen Shot 2019-08-28 at 01 54 54](https://user-images.githubusercontent.com/3432048/63813699-02456f80-c937-11e9-9a03-a662580bf9d8.png)
(no selected theme and no reply form)

Could you have a look and patch the component?

Tested with:
Joomla 3.9.11
PHP 7.2 / 7.3
JComments default template / Protostar template
Latest JComments fork

**Comment by exstreme** [comment]
Привет!
Здесь нет ошибки, потому что насколько я понимаю, для каждого языка настройки отдельно хранятся. Поэтому необходимо зайти в админку и перенастроить под каждый язык.
![2019-08-28_13-54-03](https://user-images.githubusercontent.com/18548890/63849882-a9f48900-c99b-11e9-868d-9cfd9dc2b176.png)
Особое внимание удели правам, так как там галки по умолчанию не проставлены, то и формы комментирования не будет (причем надо проставлять права с суперадмина и урезать по убыванию)

**Comment by Sulpher** [comment]
Спасибо, все так и есть. Забыл про это... :-)
Задача закрыта.
