### ISSUE TITLE
Problem with Joomla 7.x and php7

### ISSUE THREAD

**Issue by SaheraA** [exstreme/Jcomments-Recaptcha2#2]
Hi, 
thanks für working for these great module for Joomla. 
I was update it with these master-zip after I updatet Joomla to 7.2.1. 
But after change to php7 still these error: 
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; JCommentsSubscriptionManager has a deprecated constructor in /homepages/xy/yxyxyxyxyx/htdocs/xy/xyxyxyxy/components/com_jcomments/jcomments.subscription.php on line 14
Would be great, when is solving these error, that i can change finaly to php7. 
Big thanks in advance.

**Comment by exstreme** [comment]
Hi,
Thank you for testing! Did you mean Joomla 3.7.2?
Fix another deprecated, try new commit changes!

**Comment by SaheraA** [comment]
Yes, with Joomla 3.7.2. 
I try it now. Thanks.

**Comment by SaheraA** [comment]
How it's working very well and i am happy. 
Many thanks and have a great weekend.
