### ISSUE TITLE
Пустое значение CAPTCHA недопустимо - если включено кэширование

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-Recaptcha2#25]
Парни, серьезный баг.
Если в глобальной конфигурации включено Стандартное кэширование Joomla, то возникает  проблема с Invisible Captcha.

Проблема с дефолтным шаблонов из вашего форка:
![Screen Shot 2020-04-24 at 15 13 05](https://user-images.githubusercontent.com/3432048/80211477-7fe48b00-863e-11ea-9733-53f8ab5d9dc5.png)

Если отключаю стандартное кэширование - все работает
Joomla 3.9.18
JComments - последний форк, взятый у вас 
YooTheme Pro 2.0
PHP 7.3
Invisible Captcha v.2.0

**Comment by exstreme** [comment]
ПРивет, на своем тестовом сайте не наблюдаю такой проблемы, по скрину не похоже на дефолтный шаблон,  либо может в yootheme что перебивает, попробуй на Protostar проверить. Да и запросы рекапчи асинхронные, они не зависят в принципе от кеширования.

**Comment by Sulpher** [comment]
проверил - баг имеет место быть и с Protostar при включенном кэшировании.
я проверяю именно Invisible Captcha и с ней такой баг.
взгляни:
https://www.dropbox.com/s/gd9hl0uzbhren3w/jc-issue.mov?dl=0

а вот если включаю ReCaptcha, то такого бага там нет при стандартном кэшировании.
вот так:
https://www.dropbox.com/s/l4rbb4mfo3h6so8/jc-issue2.mov?dl=0

Такое впечатление, что у невидимой каптчи код некорректный.

**Comment by Sulpher** [comment]
на втором видео забыл очистить кэш после переключения, но проверил после очистки кэша - ReCaptcha работает, а Invisible - нет.

**Comment by exstreme** [comment]
Так я и не увидел отправленного комментария без кеша с невидимой рекапчей. да и она странно выглядит. 
Вообще надо смотреть консоль яваскрипта, что там приходит от гугла, может  какой конфликт.
[http://test.protectyoursite.ru/полезные-материалы/как-защитить-пароль-от-взлома](http://test.protectyoursite.ru/полезные-материалы/как-защитить-пароль-от-взлома) - у меня прекрасно отрабатывает.

**Comment by Sulpher** [comment]
> Так я и не увидел отправленного комментария без кеша с невидимой рекапчей. да и она странно выглядит.

это показано в самом начале первого видео - отключаю кэширование и тестирую отправку коммента.
касательно вида невидимой каптчи. можно вывести внизу слева, внизу справа и inline. вот то, что показано на видео - inline. в прочем, это не влияет  - ошибка проявляется, даже если выбрать другой вид (внизу слева/справа)

я проверил на 2х сайтах, размещенных на разных серверах и в обоих случаях получаю такой баг. 
могу развернуть в поддомене чистую Joomla, поставить JComments и прислать доступ.

**Comment by Globulopolis** [comment]
> Вообще надо смотреть консоль яваскрипта

Ничего там нет из ошибок. Проблема явно где-то внутри JComments.

В общем немного порыв код нашел примерно в чем проблема. При включении кеширования и при попытке отправить коммент с невидимой капчей на сервер(не гугловский) уходит пустое значение `g-recaptcha-response`.

![Clipboard01](https://user-images.githubusercontent.com/740757/80276001-0c01bb80-86ee-11ea-8e5f-f84c9da7b6c7.jpg)

Поэтому и рыгает ошибку о пустом значении капчи.
Собтно https://github.com/exstreme/Jcomments-Recaptcha2/blob/Develop/site/jcomments.ajax.php#L286 должно возвращать какой-то результат(true/false из onCheckAnswer), но диспетчер возвращает исключение.

Также `console.log(document.getElementsByName('g-recaptcha-response'));` в консоли показывает пустое значение(value) textarea капчи.

**Comment by exstreme** [comment]
Ключи вроде же как на домен выдаются, они разве могут использоваться локально?

**Comment by exstreme** [comment]
> я проверил на 2х сайтах, размещенных на разных серверах и в обоих случаях получаю такой баг.
> могу развернуть в поддомене чистую Joomla, поставить JComments и прислать доступ.

Наверно это будет оптимальным вариантом, у меня сейчас нету никакого желания и времени в угадайку играть.

**Comment by Globulopolis** [comment]
> они разве могут использоваться локально?

могут.

**Comment by exstreme** [comment]
> но диспетчер возвращает исключение

Там должен быть и какой текст ошибки

**Comment by Globulopolis** [comment]
> Там должен быть и какой текст ошибки

Вот это исключение кидает https://github.com/joomla/joomla-cms/blob/staging/plugins/captcha/recaptcha_invisible/recaptcha_invisible.php#L152

**Comment by exstreme** [comment]
Подтверждаю и у себя данную проблему. действительно тоже перестало работать. Но это больше напоминает на глюк плагина джумлы, тут по-хорошему к ним обращаться надо

**Comment by Sulpher** [comment]
Я так понимаю, что тестовый сайт не нужен, если смог у себя воспроизвести баг?
если речь идет о баге Joomla, то можно у них написать об этом  Github, только правильно сформулировать обращение нужно. Я могу помочь с переводом текста, если нужно.

**Comment by exstreme** [comment]
Да, сайт уже не нужен. По хорошему проверить это на стандартных компонентах Joomla, тогда можно будет аппрувить как баг, иначе разбирать ворох запросов и JavaScript, почему не подставляется ответ рекапчи, на что именно кеш влияет

**Comment by Sulpher** [comment]
самое простое - повесить каптчу на страницу **забыли пароль/логин?** и посмотреть поведение.
