### ISSUE TITLE
ACL Jcomment (giving simple user access backend access) 

### ISSUE THREAD

**Issue by danjde** [exstreme/Jcomments-Recaptcha2#26]
Hi Devs!
Is it possible to enable the Jcomment backend interface for a custom (not admin) user group?
from settings/permissions I don't see this feature.
Where I'm wrong?

Many many thanks!

davide

**Comment by exstreme** [comment]
/administrator/index.php?option=com_config&view=component&component=com_jcomments ?

**Comment by danjde** [comment]
Yes, normally right this one, but how set (and where properly) ACL setting to give to a different specific user group access permission?

For example, going from admin to "../administrator/index.php?option=com_config&view=component&component=com_jcomments" there is not problems, but from a different user group obtain:

> Error
> You are not authorized to view this resource.

My question is: where is it possible to set ACL properly  for each groups?
Normally from the relative options button of the component you can access these parameters, but for Jcomment I see no way to add this menu.

Could you suggest me please?

Many thanks again!


Davide

**Comment by Globulopolis** [comment]
@danjde it's required tons of work to add it. Not only add it into access.xml. Every action in controller, view, model require these changes.

**Comment by danjde** [comment]
Wow bad news this!
There is no solution it seems.


Thanks!

Davide
