### ISSUE TITLE
Спам с почты

### ISSUE THREAD

**Issue by volandku** [exstreme/Jcomments-Recaptcha2#28]
![image](https://user-images.githubusercontent.com/3468378/85683790-395eeb80-b6d6-11ea-955f-0d13831b4e2d.png)
Такие настройки по идее его должны остановить, однако странно что он идёт несмотря на рекапчу. В админке теперь  нет нового спама, но вот письма уходят

**Comment by Globulopolis** [comment]
Очередь на почтовом сервере?

**Comment by volandku** [comment]
Спам шёл за счет подписки на оповещения. Откючил эту функция. Она не закрыта каптчами
