### ISSUE TITLE
Poster problem with RSevents

### ISSUE THREAD

**Issue by Phil-War** [exstreme/Jcomments-Recaptcha2#3]
Hello,

RSevents Pro v1.10.36 - Joomla3.8.0 - PHP 7.00
If since the backoffice the comment is activated in the event then the display in frontend is on the ground with this message:
`: 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= 1420' at line 1`

verry best regards

**Comment by exstreme** [comment]
Hello!
I don't have this component, so I can't check the work of extensions and fix issue.

**Comment by Phil-War** [comment]
Hello,
I can eventually give a link or the problem will be visible, if that can help you?

**Comment by exstreme** [comment]
You need turn on debug to see wrong SQL query. Then mb we can see problem with Jcomments or with RSevents Pro.

**Comment by Phil-War** [comment]
hello,

Once the debug mode is activated "maximum" here is the message in the backend
`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgContentJComments has a deprecated constructor in /home/mydomaineprincipal/dossier_html/sousdomaine/plugins/content/jcomments/jcomments.php on line 25`
I did not get any other message than Jcomments or RSeventspro.
And in frontend always the same message, the one indicated above.

**Comment by exstreme** [comment]
Do you use another version of Jcomments without Recaptcha 2?
In this repository are already fixed problems with deprecated methods.
Trying find 1420 with phpmyadmin? Your error don't indicate full SQL query to check where is error in syntax.
Trying turn off plugin of jcomments?
