### ISSUE TITLE
Обращение к несуществующему файлу

### ISSUE THREAD

**Issue by maximys781** [exstreme/Jcomments-Recaptcha2#30]
В плагине recaptcha, **файл recaptcha.php** содержит ссылку на несуществующий файл https://www.google.com/recaptcha/api/js/recaptcha_ajax.js Может как-то актуализируете его или же наоборот удалите за ненадобностью.

**Comment by Globulopolis** [comment]
Этот плагин входит в поставку Joomla. Для его исправления лучше писать непосредственно им. https://github.com/joomla/joomla-cms/issues

**Comment by maximys781** [comment]
Ок, услышал!
