### ISSUE TITLE
Error in tpl/default/tpl_form.php v.3.0.7.6

### ISSUE THREAD

**Issue by DK9JC** [exstreme/Jcomments-Recaptcha2#36]
I get the following error:

Warning: **count():** Parameter must be an **array or an object** that implements Countable in [folder]/components/com_jcomments/tpl/default/tpl_form.php on line 210

line 210 in the code is:

        if (count($customBBCodes)) {

JComments 3.0.7.6
PHP-Version | 7.3.26-nmm1
Joomla!-Version | Joomla! 3.9.26 Stable

**Comment by exstreme** [comment]
https://github.com/exstreme/Jcomments-Recaptcha2/commit/b7c66700736718ea92fa21da52e7a8f459900f88 fixed

**Comment by DK9JC** [comment]
> 
> 
> [b7c6670](https://github.com/exstreme/Jcomments-Recaptcha2/commit/b7c66700736718ea92fa21da52e7a8f459900f88) fixed

thank you. I confirm, the issue is fixed.
