### ISSUE TITLE
PHP 7.2 Warning:  count(): Parameter must be an array or an object that implements Countable in com_jcomments/tpl/default/tpl_form.php on line 195

### ISSUE THREAD

**Issue by sozzled** [exstreme/Jcomments-Recaptcha2#4]
First of all, **_many_** thanks for creating this branch and keeping the _JComments_ extension alive.

There is a small [non fatal] warning at line 195 of the file **/components/com_jcomments/tpl/default/tpl_form.php**, namely
`		if (count($customBBCodes)) {`
This results in a warning message in PHP 7.2 "count(): Parameter must be an array or an object that implements Countable"

Replace line 195 with the following two lines in that file seems to fix the problem:
`		$len = $customBBCodes === null ? 0 : count($customBBCodes);`
`		if ($len) {`

**Comment by exstreme** [comment]
Thank you!
Cfn you check [https://github.com/exstreme/Jcomments-Recaptcha2/commit/a4062559a31259440d9be473873e9bfef1ffde10](url)
