### ISSUE TITLE
Joomla v4 - JComments prospect

### ISSUE THREAD

**Issue by fuzmic2** [exstreme/Jcomments-Recaptcha2#45]
Hi guys

I think most of you know JComments, even with the latest just updated version 3.0.7.8 the plugin will fail in Joomla 4.  We have to rename the folder "jcomments" inside "Plugin" folder to uninstall the whole package.

My question is: Any hope to get a version that can run in Jm4.  Keeping fingers crossed.

**Comment by exstreme** [comment]
Hi, Jcomments 3.x don't adapted to Joomla 4.
Use for Joomla 4 this version: https://github.com/exstreme/Jcomments-4

**Comment by fuzmic2** [comment]
Bro i can't find the zip in GitHub to download to use in joomla 4
