### ISSUE TITLE
Outside [=not the ones proposed by Jcomments]  emoticons prevent comment from being posted

### ISSUE THREAD

**Issue by fabio42170** [exstreme/Jcomments-Recaptcha2#46]
Hi !
I have installed the latest version of jcomments on Joomla! 3.10.4 Stable.
I have noticed that when someone posts a comment using his own emoticons (for example using the ones you can find on your phone with your keyboard), his comment is blocked. Meaning : the person comments, inserts his own emoticons, clicks on "send", the page is refreshed (as if the comment was published) and nothing appears !! Is there something that prevents emoticons from being inserted (I offer the possibility for my users to have access to a list of predefinied emoticons, but most of the time, it seems to be limited compared to what they actually need, so they often tend to pick their own emoticons).
Today, I had 30 users who thought their comment was sent but in fact their comments vanished in the web !!!
Thanks for your help !
Fabrice

**Comment by Globulopolis** [comment]
Using the emoticons required the utf8mb4 encoding for jcomment component tables. You can convert tables to this encoding but you will get issues this the table keys.

**Comment by fabio42170** [comment]
Thanks Vladimir for this tip. But is there no other way to prevent Jcomments from rejecting these emoticons? At least, having a message which tells the user not to use their own emoticons ? Or at least a way to prevent the user from validating his comment ? (because once they have clicked on the "send" button, they assume their comment is posted ....)

**Comment by Globulopolis** [comment]
> Thanks Vladimir for this tip. But is there no other way to prevent Jcomments from rejecting these emoticons? At least, having a message which tells the user not to use their own emoticons ? Or at least a way to prevent the user from validating his comment ? (because once they have clicked on the "send" button, they assume their comment is posted ....)

The other way is more complicated and required a lot of changes in code.
And validation in this component is very arbitrary.
I strongly recommend to change encoding and when change the lenght of the fields with keys.
You can see the changes which was made in jcomments for joomla4 here https://github.com/exstreme/Jcomments-4/tree/master/administrator/install/sql/updates/mysql

**Comment by fabio42170** [comment]
Thanks for this precision. Why should I change the "length of the fields with keys" ? And where/how (in the component ? in the database ?)
Thanks for your help!

**Comment by Globulopolis** [comment]
> Thanks for this precision. Why should I change the "length of the fields with keys" ? And where/how (in the component ? in the database ?)
> Thanks for your help!

The lenght for keys is limited to 767 bytes in mysql below 5.7.
In database. Set varchar to 100 instead of 255.

**Comment by exstreme** [comment]
You can try run fix database in administration panel with url /administrator/index.php?option=com_installer&view=database or set to utf8mb4 manually if it doesn't help

**Comment by exstreme** [comment]
> The other way is more complicated and required a lot of changes in code

I think, @fabio42170 means, that we don't have any notice or error, if comment was rejected and wasn't published. I can not reproduce this bug now, but I often faced a problem with returning any errors. And I think, that problem is still actual

**Comment by Globulopolis** [comment]
> > The other way is more complicated and required a lot of changes in code
> 
> I think, @fabio42170 means, that we don't have any notice or error, if comment was rejected and wasn't published. I can not reproduce this bug now, but I often faced a problem with returning any errors. And I think, that problem is still actual

Yes, I understand. This is really big problem, that the xomponent suppress all errors, and even more. Logic inside the component does not imply an error output.

**Comment by fabio42170** [comment]
Yes, that's exactly what I meant. It was strange to me that the component should not return any error for the user so that the user might know that something went wrong. 
In all cases, I'll try to convert the database, and I'll keep you updated !
Thanks for your lights !!

**Comment by exstreme** [comment]
![image](https://user-images.githubusercontent.com/18548890/149385109-ce8166b3-e1a9-45aa-aa59-83999232b7d7.png)
It's possible catch an error on frontend.

**Comment by fabio42170** [comment]
yes, but it's absolutely not user-friendly. What I mean is that the user does not have to look for an error in the code when sending a comment. When I wrote "It was strange to me that the component should not return any error", I meant that it would be user-friendly to have a message box appear with "you cannot send the message as it appears there are invalid symbols/characters".

**Comment by fabio42170** [comment]
> I strongly recommend to change encoding and when change the lenght of the fields with keys.

I have had a look at the 11 tables that Jcomments has in my database.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/M6xFfyK/tables.jpg" alt="tables" border="0"></a>
I have 2 questions :
1/ Should I set all of them to utf8mb4 ?
2/ What should I choose from : utf8mb4_general_ci? utf8mb4_unicode_ci?
I feel a bit lost for now. Thanks for your kind help.

**Comment by Globulopolis** [comment]
Set to all charset utf8mb4 and collation utf8mb4_unicode_ci

**Comment by fabio42170** [comment]
Well, I tried what you said :
I converted all the tables concerning jcomments to utf8mb4_unicode_ci and changed the varchar to 100 when it was originally 255 (check below an example, the _jcomments TABLE)
<a href="https://ibb.co/0n7hRzD"><img src="https://i.ibb.co/WHhg4Rx/jcomments-table.jpg" alt="jcomments-table" border="0"></a>

Now, there are 2 problems : 
1/ The comments have disappeared from the backend : 
<a href="https://ibb.co/3R9fSw8"><img src="https://i.ibb.co/CP3JVqX/joomla-jcomments-backend.jpg" alt="joomla-jcomments-backend" border="0"></a>

and from the frontend (logical it seems) : 
<a href="https://ibb.co/kHS6xvc"><img src="https://i.ibb.co/Gx530NP/joomla-jcomments-frontend.jpg" alt="joomla-jcomments-frontend" border="0"></a>

2/ The original problem still occurs : when I post a comment, and insert an external smiley, I click on send. The comment is not published at all , even if the page is refreshed. So, the comment is lost.

What could have gone wrong ?

**Comment by Globulopolis** [comment]
Field `title` is empty? Check in phpmyadmin this field.
Take a look at the php log. I think something went wrong when posting comments.

**Comment by fabio42170** [comment]
You may have misunderstood what I said. In fact, all the comments of my website (for the past 4 years) have disappeared. They don't show anymore, as you can see in the previous screenshot (the comment title column is blank)
And yet, they are still stocked in my database :
<a href="https://ibb.co/2ST14CF"><img src="https://i.ibb.co/sCZdYNg/title.jpg" alt="title" border="0"></a>

**Comment by exstreme** [comment]
> You can try run fix database in administration panel with url /administrator/index.php?option=com_installer&view=database

Did You try this solution?

**Comment by fabio42170** [comment]
Yep, this is what I got : 
	
Database is up to date.
    Database schema version (in #__schemas): 3.10.0-2021-05-28.
    Update version (in #__extensions): 3.10.4.
    Database driver: mysqli.
    189 database changes were checked.
    217 database changes did not alter table structure and were skipped.

This url is simply a database check, not a fix ?

**Comment by exstreme** [comment]
Ah, it's Joomla 3:( Unfortunately, all fixes are for Joomla 4 version

Turn on error displaying on max and debug. Then go to the Network Tab in Developers Tools (F12) and send response
![image](https://user-images.githubusercontent.com/18548890/149593165-256f75fc-e2e9-436c-8e4f-138aed3b8c8a.png)

**Comment by fabio42170** [comment]
Ok, I tried what you said, but The console does not show any errors at all.
I can't see "jcomments" at all. This is the view I've got :
<a href="https://ibb.co/fDBbz7m"><img src="https://i.ibb.co/kmkpsFY/console.jpg" alt="console" border="0"></a>
It seems that since I have transformed all the fields in utf8mb4 , even simple text messages (without emoticons) are not sent at all ... in a word, my users can't post anymore.

**Comment by exstreme** [comment]
You can scroll or filter queries. Or simple load the page, then clear all queries and then send comment

**Comment by exstreme** [comment]
You have no rights to use this tag. - When I tried to send comment

**Comment by fabio42170** [comment]
you mean you tried to send a comment live ? For public users, I do not give permission to post comments. But I have just changed this setting for you if you want to test. (and with "autopublish" ON)

**Comment by exstreme** [comment]
Still can't and can't activate account

**Comment by fabio42170** [comment]
You can't self-activate an account on my website (security to avoid being flowed with unknown users). Give me the username you tried to create an account with, and I'll activate your account (you will be a registered user then).

**Comment by exstreme** [comment]
ProtectYourSite

**Comment by fabio42170** [comment]
Activated just right now

**Comment by exstreme** [comment]
You have no rights to post comments

**Comment by fabio42170** [comment]
unlog and log in again, this should work (I changed your user group)

**Comment by exstreme** [comment]
![image](https://user-images.githubusercontent.com/18548890/149626280-a209a56e-d196-4bec-b45d-9bbf045d63fa.png)
You have still problems with tags. And your redirect hide dispaying any error

**Comment by fabio42170** [comment]
I've never had this issue before. I do believe it comes from the fact that I changed some tables from utf8 to utf8mb4 but I can't be sure about it. Is there any other possible reason for this message ?

**Comment by exstreme** [comment]
Try to turn off custom bb codes

**Comment by fabio42170** [comment]
Hey there ! Thanks for this tip. There is already progress !!😀
This solved 2 things : 
1/ I now see the comments, they are back !!
2/ I can now post comments

Yet : I **still** cannot insert personal emoticons. When I click on send, the page refreshes, and the comment is not published and has disappeared.

**Comment by exstreme** [comment]
I see only 500 error but without backtrace I cannot help. 
![image](https://user-images.githubusercontent.com/18548890/149633377-20107309-6ff5-4a18-a26c-ece134b07849.png)

**Comment by fabio42170** [comment]
backtrace? what do you mean? What do you need? (How) Can I help?

**Comment by exstreme** [comment]
https://github.com/exstreme/Jcomments-Recaptcha2/issues/46#issuecomment-1013514953

**Comment by fabio42170** [comment]
Meaning I should turn SYSTEM ERROR on inside Joomla? (in the backend?)

**Comment by exstreme** [comment]
Yes and may be debug. We can use telegram to synch our actions to prevent displaying errors for another peoople

**Comment by fabio42170** [comment]
error reporting is now turned ON. my telegram username : Teacher4u2learn

**Comment by fabio42170** [comment]
Solved thanks to exstreme & globulopolis. Was indeed a matter of utf8mb4 transformation.
