### ISSUE TITLE
PHP 7.2 issues: no fields validation and no smileys

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-Recaptcha2#9]
When I turn PHP to version 7.2, some functions don't work: no fields validation and no smileys in a comment form.
There are no such issues with PHP 7.0.

I am using your latest fork.

**Comment by exstreme** [comment]
Hello! Can you try last build?

**Comment by Sulpher** [comment]
I have downloaded the actual version, but the effect is the same with PHP 7.2.10... 
 Didn't you forget to add changes in Git? :-)

![screen shot 2018-09-29 at 13 57 41](https://user-images.githubusercontent.com/3432048/46244990-c71d8200-c3ef-11e8-9975-8670d32833b4.png)

**Comment by exstreme** [comment]
Hello!
Are you using default template or custom in Jcomments? Can you give link on page with issue?

**Comment by Sulpher** [comment]
Hi,
I made a clean installation of Joomla and your fork of JComments - all works fine.
It seems the problem is in scripts conflict on my dev site (there are many extensions installed).
